<?php
/**
 * Platforms
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Book2000App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Book2000\ApiClient\Model;
use \Book2000\ApiClient\ObjectSerializer;

/**
 * Platforms Class Doc Comment
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Platforms
{
    /**
     * Possible values of this enum
     */
    public const MARKTPLAATS = 'marktplaats';

    public const VINTED = 'vinted';

    public const DISCOGS = 'discogs';

    public const DIRECT = 'direct';

    public const OTHER = 'other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MARKTPLAATS,
            self::VINTED,
            self::DISCOGS,
            self::DIRECT,
            self::OTHER
        ];
    }
}


