<?php
/**
 * TransactionRegisterRequestInvoiceItemsInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Book2000App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Book2000\ApiClient\Model;

use \ArrayAccess;
use \Book2000\ApiClient\ObjectSerializer;

/**
 * TransactionRegisterRequestInvoiceItemsInner Class Doc Comment
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransactionRegisterRequestInvoiceItemsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TransactionRegisterRequest_invoice_items_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'description' => 'string',
        'quantity' => 'float',
        'unit_price_cents' => 'int',
        'vat_rate' => 'float',
        'subtotal_cents' => 'int',
        'vat_cents' => 'int',
        'total_cents' => 'int',
        'is_margin_goods' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'description' => null,
        'quantity' => null,
        'unit_price_cents' => null,
        'vat_rate' => null,
        'subtotal_cents' => null,
        'vat_cents' => null,
        'total_cents' => null,
        'is_margin_goods' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'description' => false,
        'quantity' => false,
        'unit_price_cents' => false,
        'vat_rate' => false,
        'subtotal_cents' => false,
        'vat_cents' => false,
        'total_cents' => false,
        'is_margin_goods' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'description' => 'description',
        'quantity' => 'quantity',
        'unit_price_cents' => 'unit_price_cents',
        'vat_rate' => 'vat_rate',
        'subtotal_cents' => 'subtotal_cents',
        'vat_cents' => 'vat_cents',
        'total_cents' => 'total_cents',
        'is_margin_goods' => 'is_margin_goods'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'description' => 'setDescription',
        'quantity' => 'setQuantity',
        'unit_price_cents' => 'setUnitPriceCents',
        'vat_rate' => 'setVatRate',
        'subtotal_cents' => 'setSubtotalCents',
        'vat_cents' => 'setVatCents',
        'total_cents' => 'setTotalCents',
        'is_margin_goods' => 'setIsMarginGoods'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'description' => 'getDescription',
        'quantity' => 'getQuantity',
        'unit_price_cents' => 'getUnitPriceCents',
        'vat_rate' => 'getVatRate',
        'subtotal_cents' => 'getSubtotalCents',
        'vat_cents' => 'getVatCents',
        'total_cents' => 'getTotalCents',
        'is_margin_goods' => 'getIsMarginGoods'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('unit_price_cents', $data ?? [], null);
        $this->setIfExists('vat_rate', $data ?? [], null);
        $this->setIfExists('subtotal_cents', $data ?? [], null);
        $this->setIfExists('vat_cents', $data ?? [], null);
        $this->setIfExists('total_cents', $data ?? [], null);
        $this->setIfExists('is_margin_goods', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ((mb_strlen($this->container['description']) > 1024)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 1024.";
        }

        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if (($this->container['quantity'] < 0)) {
            $invalidProperties[] = "invalid value for 'quantity', must be bigger than or equal to 0.";
        }

        if ($this->container['unit_price_cents'] === null) {
            $invalidProperties[] = "'unit_price_cents' can't be null";
        }
        if ($this->container['vat_rate'] === null) {
            $invalidProperties[] = "'vat_rate' can't be null";
        }
        if (($this->container['vat_rate'] < 0)) {
            $invalidProperties[] = "invalid value for 'vat_rate', must be bigger than or equal to 0.";
        }

        if ($this->container['subtotal_cents'] === null) {
            $invalidProperties[] = "'subtotal_cents' can't be null";
        }
        if ($this->container['vat_cents'] === null) {
            $invalidProperties[] = "'vat_cents' can't be null";
        }
        if ($this->container['total_cents'] === null) {
            $invalidProperties[] = "'total_cents' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $description when calling TransactionRegisterRequestInvoiceItemsInner., must be smaller than or equal to 1024.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        if (($quantity < 0)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling TransactionRegisterRequestInvoiceItemsInner., must be bigger than or equal to 0.');
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets unit_price_cents
     *
     * @return int
     */
    public function getUnitPriceCents()
    {
        return $this->container['unit_price_cents'];
    }

    /**
     * Sets unit_price_cents
     *
     * @param int $unit_price_cents unit_price_cents
     *
     * @return self
     */
    public function setUnitPriceCents($unit_price_cents)
    {
        if (is_null($unit_price_cents)) {
            throw new \InvalidArgumentException('non-nullable unit_price_cents cannot be null');
        }
        $this->container['unit_price_cents'] = $unit_price_cents;

        return $this;
    }

    /**
     * Gets vat_rate
     *
     * @return float
     */
    public function getVatRate()
    {
        return $this->container['vat_rate'];
    }

    /**
     * Sets vat_rate
     *
     * @param float $vat_rate vat_rate
     *
     * @return self
     */
    public function setVatRate($vat_rate)
    {
        if (is_null($vat_rate)) {
            throw new \InvalidArgumentException('non-nullable vat_rate cannot be null');
        }
        if (($vat_rate < 0)) {
            throw new \InvalidArgumentException('invalid value for $vat_rate when calling TransactionRegisterRequestInvoiceItemsInner., must be bigger than or equal to 0.');
        }

        $this->container['vat_rate'] = $vat_rate;

        return $this;
    }

    /**
     * Gets subtotal_cents
     *
     * @return int
     */
    public function getSubtotalCents()
    {
        return $this->container['subtotal_cents'];
    }

    /**
     * Sets subtotal_cents
     *
     * @param int $subtotal_cents subtotal_cents
     *
     * @return self
     */
    public function setSubtotalCents($subtotal_cents)
    {
        if (is_null($subtotal_cents)) {
            throw new \InvalidArgumentException('non-nullable subtotal_cents cannot be null');
        }
        $this->container['subtotal_cents'] = $subtotal_cents;

        return $this;
    }

    /**
     * Gets vat_cents
     *
     * @return int
     */
    public function getVatCents()
    {
        return $this->container['vat_cents'];
    }

    /**
     * Sets vat_cents
     *
     * @param int $vat_cents vat_cents
     *
     * @return self
     */
    public function setVatCents($vat_cents)
    {
        if (is_null($vat_cents)) {
            throw new \InvalidArgumentException('non-nullable vat_cents cannot be null');
        }
        $this->container['vat_cents'] = $vat_cents;

        return $this;
    }

    /**
     * Gets total_cents
     *
     * @return int
     */
    public function getTotalCents()
    {
        return $this->container['total_cents'];
    }

    /**
     * Sets total_cents
     *
     * @param int $total_cents total_cents
     *
     * @return self
     */
    public function setTotalCents($total_cents)
    {
        if (is_null($total_cents)) {
            throw new \InvalidArgumentException('non-nullable total_cents cannot be null');
        }
        $this->container['total_cents'] = $total_cents;

        return $this;
    }

    /**
     * Gets is_margin_goods
     *
     * @return bool|null
     */
    public function getIsMarginGoods()
    {
        return $this->container['is_margin_goods'];
    }

    /**
     * Sets is_margin_goods
     *
     * @param bool|null $is_margin_goods is_margin_goods
     *
     * @return self
     */
    public function setIsMarginGoods($is_margin_goods)
    {
        if (is_null($is_margin_goods)) {
            throw new \InvalidArgumentException('non-nullable is_margin_goods cannot be null');
        }
        $this->container['is_margin_goods'] = $is_margin_goods;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


