<?php
/**
 * TransactionRegisterRequestInvoice
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Book2000App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Book2000\ApiClient\Model;

use \ArrayAccess;
use \Book2000\ApiClient\ObjectSerializer;

/**
 * TransactionRegisterRequestInvoice Class Doc Comment
 *
 * @category Class
 * @description An optional invoice with its items.
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransactionRegisterRequestInvoice implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TransactionRegisterRequest_invoice';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'contact_id' => 'int',
        'type' => 'string',
        'invoice_reference' => 'string',
        'invoice_date' => '\DateTime',
        'due_date' => '\DateTime',
        'subtotal_cents' => 'int',
        'vat_cents' => 'int',
        'total_cents' => 'int',
        'status' => 'string',
        'items' => '\Book2000\ApiClient\Model\TransactionRegisterRequestInvoiceItemsInner[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'contact_id' => null,
        'type' => null,
        'invoice_reference' => null,
        'invoice_date' => 'date-time',
        'due_date' => 'date-time',
        'subtotal_cents' => null,
        'vat_cents' => null,
        'total_cents' => null,
        'status' => null,
        'items' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'contact_id' => false,
        'type' => false,
        'invoice_reference' => true,
        'invoice_date' => false,
        'due_date' => false,
        'subtotal_cents' => false,
        'vat_cents' => false,
        'total_cents' => false,
        'status' => false,
        'items' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contact_id' => 'contact_id',
        'type' => 'type',
        'invoice_reference' => 'invoice_reference',
        'invoice_date' => 'invoice_date',
        'due_date' => 'due_date',
        'subtotal_cents' => 'subtotal_cents',
        'vat_cents' => 'vat_cents',
        'total_cents' => 'total_cents',
        'status' => 'status',
        'items' => 'items'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contact_id' => 'setContactId',
        'type' => 'setType',
        'invoice_reference' => 'setInvoiceReference',
        'invoice_date' => 'setInvoiceDate',
        'due_date' => 'setDueDate',
        'subtotal_cents' => 'setSubtotalCents',
        'vat_cents' => 'setVatCents',
        'total_cents' => 'setTotalCents',
        'status' => 'setStatus',
        'items' => 'setItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contact_id' => 'getContactId',
        'type' => 'getType',
        'invoice_reference' => 'getInvoiceReference',
        'invoice_date' => 'getInvoiceDate',
        'due_date' => 'getDueDate',
        'subtotal_cents' => 'getSubtotalCents',
        'vat_cents' => 'getVatCents',
        'total_cents' => 'getTotalCents',
        'status' => 'getStatus',
        'items' => 'getItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('contact_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('invoice_reference', $data ?? [], null);
        $this->setIfExists('invoice_date', $data ?? [], null);
        $this->setIfExists('due_date', $data ?? [], null);
        $this->setIfExists('subtotal_cents', $data ?? [], null);
        $this->setIfExists('vat_cents', $data ?? [], null);
        $this->setIfExists('total_cents', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('items', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['type']) && (mb_strlen($this->container['type']) > 255)) {
            $invalidProperties[] = "invalid value for 'type', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['invoice_reference']) && (mb_strlen($this->container['invoice_reference']) > 255)) {
            $invalidProperties[] = "invalid value for 'invoice_reference', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['status']) && (mb_strlen($this->container['status']) > 255)) {
            $invalidProperties[] = "invalid value for 'status', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['items']) && (count($this->container['items']) < 1)) {
            $invalidProperties[] = "invalid value for 'items', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets contact_id
     *
     * @return int|null
     */
    public function getContactId()
    {
        return $this->container['contact_id'];
    }

    /**
     * Sets contact_id
     *
     * @param int|null $contact_id contact_id
     *
     * @return self
     */
    public function setContactId($contact_id)
    {
        if (is_null($contact_id)) {
            throw new \InvalidArgumentException('non-nullable contact_id cannot be null');
        }
        $this->container['contact_id'] = $contact_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        if ((mb_strlen($type) > 255)) {
            throw new \InvalidArgumentException('invalid length for $type when calling TransactionRegisterRequestInvoice., must be smaller than or equal to 255.');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets invoice_reference
     *
     * @return string|null
     */
    public function getInvoiceReference()
    {
        return $this->container['invoice_reference'];
    }

    /**
     * Sets invoice_reference
     *
     * @param string|null $invoice_reference invoice_reference
     *
     * @return self
     */
    public function setInvoiceReference($invoice_reference)
    {
        if (is_null($invoice_reference)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($invoice_reference) && (mb_strlen($invoice_reference) > 255)) {
            throw new \InvalidArgumentException('invalid length for $invoice_reference when calling TransactionRegisterRequestInvoice., must be smaller than or equal to 255.');
        }

        $this->container['invoice_reference'] = $invoice_reference;

        return $this;
    }

    /**
     * Gets invoice_date
     *
     * @return \DateTime|null
     */
    public function getInvoiceDate()
    {
        return $this->container['invoice_date'];
    }

    /**
     * Sets invoice_date
     *
     * @param \DateTime|null $invoice_date invoice_date
     *
     * @return self
     */
    public function setInvoiceDate($invoice_date)
    {
        if (is_null($invoice_date)) {
            throw new \InvalidArgumentException('non-nullable invoice_date cannot be null');
        }
        $this->container['invoice_date'] = $invoice_date;

        return $this;
    }

    /**
     * Gets due_date
     *
     * @return \DateTime|null
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     *
     * @param \DateTime|null $due_date due_date
     *
     * @return self
     */
    public function setDueDate($due_date)
    {
        if (is_null($due_date)) {
            throw new \InvalidArgumentException('non-nullable due_date cannot be null');
        }
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets subtotal_cents
     *
     * @return int|null
     */
    public function getSubtotalCents()
    {
        return $this->container['subtotal_cents'];
    }

    /**
     * Sets subtotal_cents
     *
     * @param int|null $subtotal_cents subtotal_cents
     *
     * @return self
     */
    public function setSubtotalCents($subtotal_cents)
    {
        if (is_null($subtotal_cents)) {
            throw new \InvalidArgumentException('non-nullable subtotal_cents cannot be null');
        }
        $this->container['subtotal_cents'] = $subtotal_cents;

        return $this;
    }

    /**
     * Gets vat_cents
     *
     * @return int|null
     */
    public function getVatCents()
    {
        return $this->container['vat_cents'];
    }

    /**
     * Sets vat_cents
     *
     * @param int|null $vat_cents vat_cents
     *
     * @return self
     */
    public function setVatCents($vat_cents)
    {
        if (is_null($vat_cents)) {
            throw new \InvalidArgumentException('non-nullable vat_cents cannot be null');
        }
        $this->container['vat_cents'] = $vat_cents;

        return $this;
    }

    /**
     * Gets total_cents
     *
     * @return int|null
     */
    public function getTotalCents()
    {
        return $this->container['total_cents'];
    }

    /**
     * Sets total_cents
     *
     * @param int|null $total_cents total_cents
     *
     * @return self
     */
    public function setTotalCents($total_cents)
    {
        if (is_null($total_cents)) {
            throw new \InvalidArgumentException('non-nullable total_cents cannot be null');
        }
        $this->container['total_cents'] = $total_cents;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        if ((mb_strlen($status) > 255)) {
            throw new \InvalidArgumentException('invalid length for $status when calling TransactionRegisterRequestInvoice., must be smaller than or equal to 255.');
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \Book2000\ApiClient\Model\TransactionRegisterRequestInvoiceItemsInner[]|null
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \Book2000\ApiClient\Model\TransactionRegisterRequestInvoiceItemsInner[]|null $items The optional invoice items (required as soon as an invoice is passed).
     *
     * @return self
     */
    public function setItems($items)
    {
        if (is_null($items)) {
            throw new \InvalidArgumentException('non-nullable items cannot be null');
        }

        if ((count($items) < 1)) {
            throw new \InvalidArgumentException('invalid length for $items when calling TransactionRegisterRequestInvoice., number of items must be greater than or equal to 1.');
        }
        $this->container['items'] = $items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


