<?php
/**
 * TransactionRegisterRequestJournalEntriesInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Book2000App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Book2000\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TransactionRegisterRequestJournalEntriesInnerTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionRegisterRequestJournalEntriesInner
 * @package     Book2000\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransactionRegisterRequestJournalEntriesInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransactionRegisterRequestJournalEntriesInner"
     */
    public function testTransactionRegisterRequestJournalEntriesInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ledger_code"
     */
    public function testPropertyLedgerCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount_cents"
     */
    public function testPropertyAmountCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vat_box"
     */
    public function testPropertyVatBox()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
