<?php
/**
 * TransactionRegisterRequestInvoiceItemsInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Book2000App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Book2000\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TransactionRegisterRequestInvoiceItemsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionRegisterRequestInvoiceItemsInner
 * @package     Book2000\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransactionRegisterRequestInvoiceItemsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransactionRegisterRequestInvoiceItemsInner"
     */
    public function testTransactionRegisterRequestInvoiceItemsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unit_price_cents"
     */
    public function testPropertyUnitPriceCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vat_rate"
     */
    public function testPropertyVatRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subtotal_cents"
     */
    public function testPropertySubtotalCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vat_cents"
     */
    public function testPropertyVatCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_cents"
     */
    public function testPropertyTotalCents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_margin_goods"
     */
    public function testPropertyIsMarginGoods()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
