<?php
/**
 * TransactionApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Book2000App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Book2000\ApiClient\Test\Api;

use \Book2000\ApiClient\Configuration;
use \Book2000\ApiClient\ApiException;
use \Book2000\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Book2000\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for transactionRegister
     *
     * Register a new transaction, its journal entries and an optional invoice.
     *
     */
    public function testTransactionRegister()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
